[build]
target = ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]

# https://rustwasm.github.io/wasm-bindgen/wasm-bindgen-test/usage.html
[target.wasm32-unknown-unknown]
runner = "wasm-bindgen-test-runner"
