[package]
name = "server"
version.workspace = true
authors.workspace = true
edition.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
axum = { workspace = true }
mime_guess = { workspace = true }
tokio = { workspace = true }

client = { path = "../client" }
